### ISSUE TITLE
can not train the model

### ISSUE THREAD

**Issue by simuji** [qugank/sketch-lattice.github.io#2]
Thanks for your work.
When I trian the model，it always get loss of nan，and this happens during almost same epoch.
The python packages follow the  requirements.txt but the ipython==7.33.0.
I don not know it is the version of ipython makes train wrong or other things make train wrong.

**Comment by ydyhello** [comment]
> Thanks for your work. When I trian the model，it always get loss of nan，and this happens during almost same epoch. The python packages follow the requirements.txt but the ipython==7.33.0. I don not know it is the version of ipython makes train wrong or other things make train wrong.

Hello, I have encountered the same problem as you, did you solve it?
